### ISSUE TITLE
Issue #1 Error: ENOENT: no such file or directory, mkdir; Issue #2 TimeoutError

### ISSUE THREAD

**Issue by ghost** [SibirixScrum/figma-backuper#1]
Добрый день!
К сожалению, не удаётся корректно воспользоваться.
Случай 1.
Действую согласно README на Win10 x64, Google Chrome Версия 99.0.4844.74 (Официальная сборка), (64 бит) и ChromeDriver 99.0.4844.51
Командная строка запущена от имени администратора. Выводится список проектов, однако директории не создаются. В результате получено сообщение следующего содержания.

Error: ENOENT: no such file or directory, mkdir 'C:♀igmackup\niсk\project'
    at Object.mkdirSync (node:fs:1336:3)
    at Object.createFolder (c:\backup\build\fsHelper.js:9:12)
    at Backuper.<anonymous> (c:\backup\build\backuper.js:96:26)
    at Generator.next (<anonymous>)
    at fulfilled (c:\backup\build\backuper.js:4:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -4058,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: 'C:\figma\backup\\nick\\project'
}

Случай 2.
Действую согласно README на Ubuntu 20.04.4 LTS, Google Chrome 96.0.4664.110 (Официальная сборка), (64 бит) и ChromeDriver 96.0.4664.45
Выводится список проектов, создаются директории, однако файлы не скачиваются. В результате получено сообщение следующего содержания.

waitForElementAndGet error https://www.figma.com/file/InSogJfNx8pfSMVAGEbGKA/Online> Project 3мин 2сек [class^="toolbar_view--buttonGroup"]
{ TimeoutError: Waiting for element to be located By(css selector, [class^="toolbar_view--buttonGroup"])
Wait timed out after 180122ms
    at /home/kid/figma-backuper-master/node_modules/selenium-webdriver/lib/webdriver.js:901:17
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'TimeoutError', remoteStacktrace: '' }

Прошу подсказки: в чём я ошибаюсь. Спасибо.

**Comment by SibirixScrum** [comment]
1. Подскажите, папка C:\figmackup - существует? Windows 10 может не давать создавать папки в корне системного диска. Если не существует - попробуйте создать её вручную и запустите скрипт снова.
2. видимо скачиваемый файл достаточно большой, и не успевает скачаться за 3 минуты (зашитое в скриптах время ожидания загрузки файла). Вынесли это время в настройки (+ увеличили дефолтное время ожидания до 5 минут) - посмотрите в примере конфига параметр delayFileDownloadSeconds, и увеличьте его если будет падать та же ошибка. К сожалению это может не помочь - фигма очень неторопливо конвертирует большие файлы и достаточно часто виснет полностью.

**Comment by toimi-git** [comment]
Столкнулся с такой же проблемой. Целевую папку для скачивания нужно размещать в той же директории, где находится package.json, тогда скрипт работает. По крайней мере, мне это помогло (Windows 10). Пожалуйста, добавьте это в readme, если я прав

**Comment by ghost** [comment]
1. Я полагаю, что в моём случае путь C:♀igmackup выводится в терминале некорректно. Пробовал создавать C:\figmackup вручную - к сожалению, это не помогло. Изначально в файле config.json данный параметр указан как:
"baseFolder": "C:\figma\backup",
Директория C:\figma\backup была создана предварительно.

2. В качестве эксперимента запускал скрипт около 10 раз с установленным временем ожидания 5 минут . Также пробовал увеличивать время ожидания загрузки до 30 минут. Результат всё тот же.

Благодарю за ответы.

**Comment by ghost** [comment]
@toimi-git Вы правы.
1. Изменил значение параметра "baseFolder" в конфигурационном файле с абсолютного пути на относительный - проблема "Error: ENOENT: no such file or directory, mkdir" более не возникает, директории внутри создаются.
Однако вес созданной папки остаётся 0 байт даже спустя несколько часов. Файлы не скачиваются.

**Comment by SibirixScrum** [comment]
> 1. путь C:♀igmackup выводится в терминале некорректно.
Github некорректно вывел текст в readme - в конфиге для Windows надо указывать двойные слеши в пути до папки:
"C:\\figma\\backup". В исходном коде ридми-файла указаны как раз двойные слеши.

**Comment by SibirixScrum** [comment]
> 2. В качестве эксперимента запускал скрипт около 10 раз с установленным временем ожидания 5 минут .
Вы пробовали сохранить этот файл через саму фигму? Через пункт меню File - Save local Copy? сколько времени занимает сохранение?

Если у вас в логе при этом ошибка:
"{ TimeoutError: Waiting for element to be located By(css selector, [class^="toolbar_view--buttonGroup"])"
Это означает, что скрипт либо не смог перейти на страницу макета, либо она не открылась/не доступна.

Чтобы проверить эту проблему запустите скрипт в режиме дебага (--debug)
Дождитесь строки
    driver.get(link) https://www.figma.com/file/.......
и попробуйте открыть эту ссылку в браузере самостоятельно = проверьте есть ли какая-либо ошибка.
